#!/usr/bin/env node
/* ==========================================================================
   cli.mjs — the skill's deterministic wrapper around the D&D 2024 engine.
   HAND-AUTHORED (not generated by build-bundles). Reuses resolver.mjs +
   build-character.mjs (generated copies) and the data/ catalogue.

   Commands:
     node engine/cli.mjs options <answers.json>            list the next legal choices
     node engine/cli.mjs build   <answers.json> [--lang en] answers -> model -> sheet + lint
     node engine/cli.mjs check   <model.character.json>     lint/compute an existing model

   Exit code is non-zero when the sheet has rules errors. This is the tool the
   skills MUST call instead of computing D&D math from memory. See ../rules/grounding.md.
   ========================================================================== */
import { readFileSync } from "node:fs";
import { computeCharacter } from "./build-character.mjs";
import {
  loadCatalogNode, pendingChoices, toCharacterModel,
  fixedNodeOptions, nodeApplies,
} from "./resolver.mjs";

/* ---- i18n (small, stable tables live here; entity names come from labels.en.json) ---- */
const ABILITY_FR = { str: "Force", dex: "Dextérité", con: "Constitution", int: "Intelligence", wis: "Sagesse", cha: "Charisme" };
const ABILITY_EN = { str: "Strength", dex: "Dexterity", con: "Constitution", int: "Intelligence", wis: "Wisdom", cha: "Charisma" };
const T = {
  fr: { ac: "CA", hp: "Points de vie", init: "Initiative", pp: "Perception passive", pb: "Bonus de maitrise",
    saves: "Jets de sauvegarde", skills: "Compétences", spells: "Sorts", cantrips: "Sorts mineurs",
    prepared: "Sorts préparés", equipment: "Équipement", provenance: "provenance", remaining: "Choix restants",
    conflicts: "Conflits", lintOk: "sheet-lint : 0 erreur.", lintErr: "erreur(s)", none: "aucun", level: "niveau" },
  en: { ac: "AC", hp: "Hit Points", init: "Initiative", pp: "Passive Perception", pb: "Proficiency Bonus",
    saves: "Saving throws", skills: "Skills", spells: "Spells", cantrips: "Cantrips",
    prepared: "Prepared spells", equipment: "Equipment", provenance: "provenance", remaining: "Choices remaining",
    conflicts: "Conflicts", lintOk: "sheet-lint: 0 error.", lintErr: "error(s)", none: "none", level: "level" },
  de: { ac: "RK", hp: "Trefferpunkte", init: "Initiative", pp: "Passive Wahrnehmung", pb: "Übungsbonus",
    saves: "Rettungswürfe", skills: "Fertigkeiten", spells: "Zauber", cantrips: "Zaubertricks",
    prepared: "Vorbereitete Zauber", equipment: "Ausrüstung", provenance: "Quelle", remaining: "Verbleibende Auswahl",
    conflicts: "Konflikte", lintOk: "sheet-lint: 0 Fehler.", lintErr: "Fehler", none: "keine", level: "Stufe" },
  es: { ac: "CA", hp: "Puntos de golpe", init: "Iniciativa", pp: "Percepción pasiva", pb: "Bonificador de competencia",
    saves: "Tiradas de salvación", skills: "Habilidades", spells: "Conjuros", cantrips: "Trucos",
    prepared: "Conjuros preparados", equipment: "Equipo", provenance: "fuente", remaining: "Opciones restantes",
    conflicts: "Conflictos", lintOk: "sheet-lint: 0 errores.", lintErr: "error(es)", none: "ninguno", level: "nivel" },
  it: { ac: "CA", hp: "Punti ferita", init: "Iniziativa", pp: "Percezione passiva", pb: "Bonus competenza",
    saves: "Tiri salvezza", skills: "Abilità", spells: "Incantesimi", cantrips: "Trucchetti",
    prepared: "Incantesimi preparati", equipment: "Equipaggiamento", provenance: "fonte", remaining: "Scelte rimanenti",
    conflicts: "Conflitti", lintOk: "sheet-lint: 0 errori.", lintErr: "errore/i", none: "nessuno", level: "livello" },
  ja: { ac: "AC", hp: "ヒット・ポイント", init: "イニシアチブ", pp: "受動判断力（知覚）", pb: "習熟ボーナス",
    saves: "セービング・スロー", skills: "技能", spells: "呪文", cantrips: "キャントリップ",
    prepared: "準備済み呪文", equipment: "装備", provenance: "出典", remaining: "残りの選択",
    conflicts: "競合", lintOk: "sheet-lint: エラー0件。", lintErr: "エラー", none: "なし", level: "レベル" },
  ru: { ac: "КД", hp: "Хиты", init: "Инициатива", pp: "Пассивное восприятие", pb: "Бонус мастерства",
    saves: "Спасброски", skills: "Навыки", spells: "Заклинания", cantrips: "Заговоры",
    prepared: "Подготовленные заклинания", equipment: "Снаряжение", provenance: "источник", remaining: "Оставшиеся выборы",
    conflicts: "Конфликты", lintOk: "sheet-lint: 0 ошибок.", lintErr: "ошибок", none: "нет", level: "уровень" },
  zh: { ac: "护甲等级", hp: "生命值", init: "先攻", pp: "被动感知", pb: "熟练加值",
    saves: "豁免", skills: "技能", spells: "法术", cantrips: "戏法",
    prepared: "已准备法术", equipment: "装备", provenance: "来源", remaining: "剩余选择",
    conflicts: "冲突", lintOk: "sheet-lint: 0错误。", lintErr: "错误", none: "无", level: "等级" },
  ar: { ac: "درع", hp: "نقاط الضربة", init: "مبادرة", pp: "الإدراك السلبي", pb: "مكافأة الكفاءة",
    saves: "رميات الإنقاذ", skills: "المهارات", spells: "التعويذات", cantrips: "التعويذات الخفيفة",
    prepared: "التعويذات المحضَّرة", equipment: "المعدات", provenance: "مصدر", remaining: "الخيارات المتبقية",
    conflicts: "تعارضات", lintOk: "sheet-lint: 0 أخطاء.", lintErr: "خطأ/أخطاء", none: "لا شيء", level: "مستوى" },
};

function loadLabels(lang = "en") {
  try {
    const url = new URL(`../data/labels.${lang}.json`, import.meta.url);
    return JSON.parse(readFileSync(url, "utf8"));
  } catch {
    try {
      const url = new URL("../data/labels.en.json", import.meta.url);
      return JSON.parse(readFileSync(url, "utf8"));
    } catch { return {}; }
  }
}

function makeLabeler(lang, labels) {
  const en = lang === "en";
  const abil = (a) => (labels.abilities && labels.abilities[a]) || (lang === "fr" ? ABILITY_FR : ABILITY_EN)[a] || a;
  const map = (group, id, fallback) => (labels[group] && labels[group][id]) || fallback || id;
  return { en, abil, map };
}

const sign = (n) => (n >= 0 ? "+" + n : "" + n);

/* ---- options : the next legal choices, straight from the resolver ---- */
function cmdOptions(answers) {
  const catalog = loadCatalogNodeSync(); // resolver.loadCatalogNode is async; wrap below
  return catalog.then((cat) => {
    const fixed = [];
    for (const step of cat.graph.steps) {
      for (const node of step.nodes) {
        if (!nodeApplies(cat, answers, node)) continue;
        if (node.type === "single" && answers[node.id] == null) {
          fixed.push({ id: node.id, label: node.label, type: "single", options: fixedNodeOptions(cat, answers, node) });
        } else if (node.type === "ability-scores" && !answers.abilityScores) {
          fixed.push({ id: "abilityScores", label: node.label, type: "ability-scores", methods: cat.graph.abilityMethods });
        }
      }
    }
    const dynamic = pendingChoices(cat, answers)
      .filter((c) => !c.satisfied)
      .map((c) => ({ id: c.id, kind: c.kind, source: c.sourceLabel, need: c.need,
        options: c.options, recommendations: c.recommendations }));
    const ready = fixed.length === 0 && dynamic.length === 0 && !!answers.abilityScores;
    return { ready, fixedPending: fixed, dynamicPending: dynamic };
  });
}

/* resolver.loadCatalogNode is async; keep one shared promise. */
let _catalog = null;
function loadCatalogNodeSync() { return (_catalog ||= loadCatalogNode()); }

/* ---- markdown sheet ---- */
function renderSheet(C, lang, labels) {
  const L = makeLabeler(lang, labels);
  const t = T[lang] || T.en;
  const id = C.model.identity || {};
  const A = ["str", "dex", "con", "int", "wis", "cha"];
  const out = [];

  const clsName = L.map("classes", (C.model.sources.find((s) => s.kind === "class-level") || {}).id, id.className);
  const spName = L.map("species", (C.model.sources.find((s) => s.kind === "species") || {}).id, id.species);
  out.push(`# ${id.name || "?"}`);
  out.push(`*${spName || "?"}${id.lineage ? " (" + id.lineage + ")" : ""}, ${clsName || "?"} ${t.level} ${C.lvl}${id.background ? ", " + id.background : ""}.*`);
  out.push("");

  // ability scores
  out.push("| " + A.map((a) => L.abil(a).slice(0, 3)).join(" | ") + " |");
  out.push("|" + A.map(() => "---").join("|") + "|");
  out.push("| " + A.map((a) => `${C.scores[a] ?? "?"} (${sign(C.mods[a])})`).join(" | ") + " |");
  out.push("");

  // core derived
  const pick = (name) => C.derived.find((d) => d.name === name);
  const core = [
    [t.pb, sign(C.PB), `PB`],
    [t.hp, (pick("Points de vie") || {}).value, (pick("Points de vie") || {}).prov],
    [t.ac, (pick("CA") || {}).value, (pick("CA") || {}).prov],
    [t.init, (pick("Initiative") || {}).value, `mod Dex`],
    [t.pp, (pick("Perception passive") || {}).value, (pick("Perception passive") || {}).prov],
  ];
  for (const [k, v, prov] of core) out.push(`- **${k}**: ${v} _(${t.provenance}: ${prov})_`);
  out.push("");

  // saves
  out.push(`## ${t.saves}`);
  out.push(C.saves.map((s) => `${L.abil(s.a).slice(0, 3)} ${sign(s.total)}${s.prof ? "*" : ""}`).join(" · "));
  out.push("");

  // skills (proficient only, to stay under Vercel-style volume discipline)
  const prof = C.skills.filter((s) => s.prof);
  if (prof.length) {
    out.push(`## ${t.skills}`);
    out.push(prof.map((s) => `${L.map("skills", s.name, s.name)} ${sign(s.total)}${s.exp ? "**" : "*"} _(${s.src || ""})_`).join("\n"));
    out.push("");
  }

  // spells
  if (C.cantrips.length || C.prepared.length) {
    out.push(`## ${t.spells}`);
    C.castingRows.forEach((r) => out.push(`- ${r.list}: DC ${r.dc} / atk ${sign(r.atk)}`));
    if (C.cantrips.length) out.push(`**${t.cantrips}**: ` + C.cantrips.map((s) => L.map("spells", s.id, s.label || s.id)).join(", "));
    if (C.prepared.length) out.push(`**${t.prepared}**: ` + C.prepared.map((s) => L.map("spells", s.id, s.label || s.id)).join(", "));
    out.push("");
  }

  // equipment
  if ((C.model.equipment || []).length) {
    out.push(`## ${t.equipment}`);
    out.push(C.model.equipment.map((e) => `- ${e.object} (${(e.roles || []).join(", ")})`).join("\n"));
    out.push("");
  }

  // remaining / conflicts / lint
  out.push(`## Lint`);
  out.push(`- ${t.remaining}: ${C.missing.length ? C.missing.map((m) => `${m.kind}×${m.count}`).join(", ") : t.none}`);
  out.push(`- ${t.conflicts}: ${C.conflicts.length ? C.conflicts.map((c) => c.what).join(", ") : t.none}`);
  const errs = C.problems.filter((p) => p.level === "error");
  out.push(errs.length ? `- ⛔ ${errs.length} ${t.lintErr}: ${errs.map((p) => p.msg).join(" ; ")}` : `- ✅ ${t.lintOk}`);
  return out.join("\n");
}

/* ---- runners ---- */
function readJSON(path) { return JSON.parse(readFileSync(path, "utf8")); }

async function run() {
  const [cmd, file, ...rest] = process.argv.slice(2);
  const lang = rest.includes("--lang") ? rest[rest.indexOf("--lang") + 1] : "fr";
  if (!cmd || !file) {
    console.error("usage: node engine/cli.mjs <options|build|check> <file.json> [--lang en]");
    process.exit(2);
  }

  if (cmd === "options") {
    const res = await cmdOptions(readJSON(file));
    console.log(JSON.stringify(res, null, 2));
    process.exit(0);
  }

  if (cmd === "build" || cmd === "check") {
    let model;
    if (cmd === "build") {
      const cat = await loadCatalogNodeSync();
      model = toCharacterModel(cat, readJSON(file));
    } else {
      model = readJSON(file);
    }
    const C = computeCharacter(model);
    const labels = loadLabels(lang);
    console.log(renderSheet(C, lang, labels));
    const errs = C.problems.filter((p) => p.level === "error");
    process.exit(errs.length ? 1 : 0);
  }

  console.error(`unknown command: ${cmd}`);
  process.exit(2);
}

run().catch((e) => { console.error(e.stack || String(e)); process.exit(2); });
