#!/usr/bin/env node
/* GENERATED by scripts/build-adapters.mjs — do not edit. */
/* dnd.mjs — run the Dungeons & Skills engine from inside a skill folder.

   This shim is the skill's only door to the engine. It locates engine/cli.mjs
   by walking up from its own location — a repo checkout, an installed .claude/
   tree and a plugin root all resolve — then forwards its arguments and the
   engine's exit code unchanged.

   Requires Node.js 18+. Non-interactive: it never prompts, so it is safe to run
   unattended. HTML builds and explicit --output paths write deterministic artifacts.
*/
import { existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HELP = `Usage: node scripts/dnd.mjs <command> [args]

Run the deterministic D&D 2024 engine that backs this skill. Every rules value
comes from the bundled catalog — never from the model's memory.

Commands:
  options     <answers.json> [--brief] [--only <id>]
                                           List the next legal choices (JSON on stdout).
                                           A full list can exceed 13K chars, which some
                                           harnesses truncate silently. --brief gives ids
                                           and option counts only; --only <id> gives the
                                           full options for one choice. Walk with --brief,
                                           then fetch each choice with --only.
  build       <answers.json> [--format html|markdown|json] [--lang xx]
              [--output file] [--json]      Build the sheet, then lint it. Defaults
                                           to standalone HTML beside the input.
  check       <model.character.json> [--format html|markdown|json] [--lang xx]
              [--output file] [--json]      Lint/compute an existing sheet. Defaults
                                           to Markdown on stdout.
  progression <classId|subclassId>         Level 1-20 milestones (proficiency bonus,
                                           features, spell slots, ASI levels), each
                                           row citing its source table.
  doctor                                   Report the installation as it actually is:
                                           resolved paths, catalog counts read from
                                           disk, per-language label coverage. Exits 2
                                           when the rules bundle is missing.

--json is the backward-compatible alias of --format json and gives machine-readable
derived values on stdout. --output is available for HTML and Markdown, not JSON.

Languages: en fr de es it ja ru zh ar. The engine defaults to en when --lang is
omitted. The options command does not yet honour --lang.

Exit codes:
  0  success — for \`build\` and \`check\`, the sheet has 0 rules errors
  1  the sheet has rules errors, is incomplete, or names something not in the catalog
  2  the engine was not found (the rules bundle is not installed) — and only that
  3  bad input or usage — unreadable file, invalid JSON, unknown command or --lang
  4  the engine crashed (a bug); not a missing bundle and not a bad sheet

\`--help\` prints this text and exits 0 without looking for the engine, so it does
NOT prove the bundle is installed. Use \`doctor\` for that — it reads the catalog.

HTML writes a deterministic .sheet.<lang>.html or .audit.<lang>.html beside its
input unless --output is provided. Markdown and JSON default to stdout.

Run it by its path inside THIS skill's folder. A bare \`scripts/dnd.mjs\` only
resolves when the shell's working directory is the skill folder, which it
usually is not:
  node "\$SKILL_DIR/scripts/dnd.mjs" options answers.json

Examples:
  node scripts/dnd.mjs options answers.json
  node scripts/dnd.mjs build answers.json --lang fr
`;

/* Walk up from this file only, and require a sibling data/ before accepting a
   candidate. Two reasons: an unrelated engine/cli.mjs without the catalog is
   useless, and the previous process.cwd() fallback would spawn whatever
   engine/cli.mjs happened to sit above the caller's directory.

   At each level, also probe the two conventional agent directories. A skill
   installed under .agents/skills/ sits at the same depth as one under
   .claude/skills/, but the bundle is written once — without this the neutral
   tree resolves nothing, and hand-copying a skill folder into a project that
   already has the bundle fails closed for no reason. The sibling-data/ rule is
   applied to every candidate, so a bare engine/ still never wins. */
const ROOTS = ["", ".claude", ".agents"];

/* The catalog's own filenames are the identity check, not the mere presence of a
   data/ directory. `engine/` + `data/` is a generic pairing: any project that
   happens to have both used to win the walk, and this shim would spawn a STRANGER'S
   engine/cli.mjs with the skill's arguments and forward its exit code as a rules
   answer. Exit 0 from that script satisfies the install gate every skill body
   defines, and every value in the session after it is ungrounded while looking
   verified. */
const MARKERS = ["build-graph.json", "classes.json", "progression.json"];

function findEngine(start) {
  let dir = start;
  for (let depth = 0; depth < 12; depth++) {
    for (const root of ROOTS) {
      const base = root ? join(dir, root) : dir;
      const candidate = join(base, "engine", "cli.mjs");
      if (existsSync(candidate) && MARKERS.every((f) => existsSync(join(base, "data", f)))) return candidate;
    }
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
  return null;
}

const args = process.argv.slice(2);
// Any --help anywhere: per-command help used to reach the engine as a filename
// and come back as a stack trace with the bundle-missing exit code.
if (args.includes("--help") || args.includes("-h")) {
  process.stdout.write(HELP);
  process.exit(0);
}
if (args.length === 0) {
  process.stderr.write(HELP);
  process.exit(3);
}

const here = dirname(fileURLToPath(import.meta.url));
const engine = findEngine(here);

if (!engine) {
  process.stderr.write(
    "dnd.mjs: cannot find the Dungeons & Skills engine (engine/cli.mjs).\n" +
    "This skill needs the rules bundle installed alongside it. The bundled catalog\n" +
    "is the only legal source of D&D 2024 values, so there is nothing to fall back\n" +
    "on — do not compute the sheet from memory.\n" +
    "Install it from:  https://github.com/mlabarrere/dungeons-and-skills/releases\n" +
    "Searched upward from " + here + " — 12 levels, probing <dir>/, <dir>/.claude/ and\n" +
    "<dir>/.agents/ at each, and requiring data/build-graph.json beside engine/cli.mjs.\n" +
    "The working directory is NOT searched: this shim resolves only from its own location.\n");
  process.exit(2);
}

const result = spawnSync(process.execPath, [engine, ...args], { stdio: "inherit" });
// A signal death is not a rules result. Forwarding it as 1 told the agent its sheet
// was illegal when the engine had been OOM-killed.
if (result.signal) {
  process.stderr.write("dnd.mjs: the engine was killed by " + result.signal + " — out of memory or an\n" +
    "external kill. This is not a rules verdict; nothing about the sheet was decided.\n");
  process.exit(4);
}
process.exit(result.status === null ? 4 : result.status);
