#!/usr/bin/env node
/* ==========================================================================
   cli.mjs — the skill's deterministic wrapper around the D&D 2024 engine.
   HAND-AUTHORED (not generated by build-bundles). Reuses resolver.mjs +
   build-character.mjs (generated copies) and the data/ catalogue.

   Commands:
     node engine/cli.mjs options <answers.json>            list the next legal choices
     node engine/cli.mjs build <answers.json> [--format html|markdown|json] [--lang en] [--output file]
     node engine/cli.mjs check <model.character.json> [--format html|markdown|json] [--lang en] [--output file]
     node engine/cli.mjs progression <classId|subclassId>  level 1-20 milestones + provenance

   Exit code is non-zero when the sheet has rules errors. This is the tool the
   skills MUST call instead of computing D&D math from memory. See ../rules/grounding.md.
   ========================================================================== */
import { existsSync, mkdirSync, readFileSync, realpathSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { basename, dirname, extname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { computeCharacter } from "./build-character.mjs";
import { renderHTML, renderMarkdown } from "./render-character.mjs";
import {
  pendingChoices, toCharacterModel,
  fixedNodeOptions, nodeApplies, normId,
} from "./resolver.mjs";

/* ---- i18n (data-driven) ---- entity names come from data/labels.<lang>.json;
   sheet chrome (section headings / fixed labels) from data/ui-labels.json. */
const ABILITY_FR = { str: "Force", dex: "Dextérité", con: "Constitution", int: "Intelligence", wis: "Sagesse", cha: "Charisme" };
const ABILITY_EN = { str: "Strength", dex: "Dexterity", con: "Constitution", int: "Intelligence", wis: "Wisdom", cha: "Charisma" };

const CATALOG_SCHEMA_VERSION = 1;
const CATALOG_PROFILE = "srd-5.2";
const CATALOG_RULESET = "2024";
const CATALOG_LICENSE = "CC-BY-4.0";
const CATALOG_MANIFEST = "catalog-manifest.json";
const REQUIRED_CATALOG_FILES = [
  "classes.json", "subclasses.json", "species.json", "backgrounds.json",
  "feats.json", "equipment.json", "spells.json", "spells-by-class.json",
  "languages.json", "conditions.json", "build-graph.json", "progression.json",
  "labels.en.json", "ui-labels.json",
];
const BUNDLED_CATALOG_DIR = fileURLToPath(new URL("../data/", import.meta.url));

let _catalogConfig = null;
let _catalog = null;
const _dataCache = new Map();

function manifestFileMap(manifest) {
  if (!manifest.files || typeof manifest.files !== "object" || Array.isArray(manifest.files)) return null;
  const out = new Map();
  for (const [key, raw] of Object.entries(manifest.files)) {
    const descriptor = typeof raw === "string"
      ? (/^[a-f0-9]{64}$/i.test(raw) ? { path: key, sha256: raw } : { path: raw })
      : (raw && typeof raw === "object" ? { path: key, ...raw } : null);
    if (!descriptor || typeof descriptor.path !== "string" || !descriptor.path.trim()) continue;
    out.set(key, descriptor);
    out.set(descriptor.path.replaceAll("\\", "/"), descriptor);
    out.set(basename(descriptor.path), descriptor);
  }
  return out;
}

function catalogDescriptor(config, rel) {
  return config.fileMap?.get(rel) || null;
}

function catalogFilePath(config, rel) {
  const descriptor = catalogDescriptor(config, rel);
  if (!descriptor) throw new Error(`catalog manifest does not declare ${rel}`);
  const declared = descriptor.path;
  if (isAbsolute(declared)) throw new Error(`catalog manifest path must be relative: ${declared}`);
  const absolute = resolve(config.dir, declared);
  const inside = relative(config.dir, absolute);
  if (!inside || inside.startsWith("..") || isAbsolute(inside))
    throw new Error(`catalog manifest path escapes its directory: ${declared}`);
  return absolute;
}

function validateCatalogFileSchema(rel, value) {
  const entityArrays = new Set([
    "classes.json", "subclasses.json", "species.json", "backgrounds.json",
    "feats.json", "spells.json", "conditions.json",
  ]);
  if (entityArrays.has(rel)) {
    if (!Array.isArray(value)) return `${rel} must contain an array`;
    const invalid = value.findIndex((entry) => !entry || typeof entry !== "object" || typeof entry.id !== "string" || !entry.id);
    return invalid < 0 ? null : `${rel}[${invalid}] must have a non-empty string id`;
  }
  if (rel === "equipment.json") {
    if (!value || typeof value !== "object" || Array.isArray(value)) return `${rel} must contain grouped arrays`;
    for (const group of ["weapons", "armors", "tools", "packs", "gear"])
      if (!Array.isArray(value[group])) return `${rel}.${group} must be an array`;
    return null;
  }
  if (rel === "languages.json") {
    return value && Array.isArray(value.courantes) && Array.isArray(value.rares)
      ? null : `${rel} must contain courantes[] and rares[]`;
  }
  if (rel === "spells-by-class.json") {
    if (!value || typeof value !== "object" || Array.isArray(value)) return `${rel} must contain a class map`;
    return Object.values(value).every(Array.isArray) ? null : `${rel} class entries must be arrays`;
  }
  if (rel === "build-graph.json")
    return value && Array.isArray(value.steps) ? null : `${rel} must contain steps[]`;
  if (rel === "progression.json")
    return value && value.classes && typeof value.classes === "object" ? null : `${rel} must contain a classes object`;
  if (rel.startsWith("labels.") || rel === "ui-labels.json")
    return value && typeof value === "object" && !Array.isArray(value) ? null : `${rel} must contain an object`;
  return null;
}

function validateCatalogSelection(dir, source) {
  const config = {
    source, dir: resolve(dir), manifestPath: resolve(dir, CATALOG_MANIFEST),
    manifest: null, fileMap: null, errors: [], warnings: [],
  };
  try {
    if (!existsSync(config.dir) || !statSync(config.dir).isDirectory())
      throw new Error(`catalog directory does not exist: ${config.dir}`);
    if (!existsSync(config.manifestPath))
      throw new Error(`catalog manifest missing: ${config.manifestPath}`);
    config.manifest = JSON.parse(readFileSync(config.manifestPath, "utf8"));
  } catch (error) {
    config.errors.push(error.message);
    return config;
  }
  const manifest = config.manifest;
  const expected = [
    ["schemaVersion", CATALOG_SCHEMA_VERSION],
    ["profile", CATALOG_PROFILE],
    ["ruleset", CATALOG_RULESET],
    ["license", CATALOG_LICENSE],
  ];
  for (const [key, value] of expected) {
    if (manifest[key] !== value)
      config.errors.push(`catalog manifest ${key} must be ${JSON.stringify(value)} (got ${JSON.stringify(manifest[key])})`);
  }
  if (typeof manifest.version !== "string" || !manifest.version.trim())
    config.errors.push("catalog manifest version must be a non-empty string");
  config.fileMap = manifestFileMap(manifest);
  if (!config.fileMap) {
    config.errors.push("catalog manifest files must be an object of path descriptors");
    return config;
  }
  for (const rel of REQUIRED_CATALOG_FILES)
    if (!catalogDescriptor(config, rel)) config.errors.push(`catalog manifest does not declare ${rel}`);

  const descriptors = [...new Set(config.fileMap.values())];
  for (const descriptor of descriptors) {
    const rel = descriptor.path.replaceAll("\\", "/");
    try {
      const path = catalogFilePath(config, rel);
      if (!existsSync(path) || !statSync(path).isFile()) throw new Error(`catalog file missing: ${path}`);
      const realDir = realpathSync(config.dir);
      const realFile = realpathSync(path);
      const realInside = relative(realDir, realFile);
      if (!realInside || realInside.startsWith("..") || isAbsolute(realInside))
        throw new Error(`catalog file resolves outside its directory: ${rel}`);
      const bytes = readFileSync(path);
      const value = JSON.parse(bytes.toString("utf8"));
      const schemaError = validateCatalogFileSchema(basename(rel), value);
      if (schemaError) throw new Error(`catalog schema error: ${schemaError}`);
      if (descriptor.sha256 != null) {
        if (!/^[a-f0-9]{64}$/i.test(descriptor.sha256))
          throw new Error(`catalog manifest has invalid sha256 for ${rel}`);
        const actual = createHash("sha256").update(bytes).digest("hex");
        if (actual.toLowerCase() !== descriptor.sha256.toLowerCase())
          throw new Error(`catalog checksum mismatch for ${rel}`);
      }
    } catch (error) {
      config.errors.push(error.message);
    }
  }
  return config;
}

function configureCatalog(cliDir = null) {
  const envDir = String(process.env.DND_SKILLS_CATALOG_DIR || "").trim();
  const source = cliDir ? "cli" : envDir ? "environment" : "bundled";
  const dir = cliDir || envDir || BUNDLED_CATALOG_DIR;
  _catalogConfig = validateCatalogSelection(dir, source);
  _catalog = null;
  _dataCache.clear();
  return _catalogConfig;
}

function loadData(rel) {
  if (!_catalogConfig) configureCatalog();
  if (_catalogConfig.errors.length) throw new Error(_catalogConfig.errors.join("; "));
  if (!_dataCache.has(rel)) {
    const path = catalogFilePath(_catalogConfig, rel);
    _dataCache.set(rel, JSON.parse(readFileSync(path, "utf8")));
  }
  return _dataCache.get(rel);
}

function loadUiLabels() {
  try { return loadData("ui-labels.json"); } catch { return {}; }
}

function loadLabels(lang = "en") {
  try {
    return loadData(`labels.${lang}.json`);
  } catch {
    try { return loadData("labels.en.json"); } catch { return {}; }
  }
}

function makeLabeler(lang, labels) {
  const en = lang === "en";
  const abil = (a) => (labels.abilities && labels.abilities[a]) || (lang === "fr" ? ABILITY_FR : ABILITY_EN)[a] || a;
  const map = (group, id, fallback) => (labels[group] && labels[group][id]) || fallback || id;
  return { en, abil, map };
}

const sign = (n) => (n >= 0 ? "+" + n : "" + n);

/* ---- answer validation -------------------------------------------------
   The resolver treats "answered" as "the key is not null". That is not the
   same as "answered legally": a hallucinated class id (`"class":"warlord"`)
   is non-null, so it drops out of `fixedPending` and the sheet is computed
   from nothing — rendering `undefined` values under a green lint.

   That is the exact failure this whole toolchain exists to prevent, so every
   answered value is checked against the legal option set the resolver itself
   returns, and an unknown id is a hard error, never a silent default. */
const META_KEYS = new Set(["_id", "id", "name", "nom", "alignment", "alignement", "abilityScores", "method", "methode"]);

async function validateAnswers(cat, answers) {
  const problems = [];
  const known = new Set(META_KEYS);

  for (const step of cat.graph.steps) {
    for (const node of step.nodes) {
      known.add(node.id);
      if (node.type !== "single" || !nodeApplies(cat, answers, node)) continue;
      const given = answers[node.id];
      if (given == null) continue;
      const legal = fixedNodeOptions(cat, answers, node).map((o) => o.id);
      if (!legal.includes(given)) {
        problems.push(`Manquant documentaire : "${given}" is not a legal value for "${node.id}". Legal ids: ${legal.join(", ")}`);
      }
    }
  }

  // Options are de-duplicated against everything already granted — including what
  // THIS key granted, and what a downstream choice re-granted from it (rogue
  // expertise draws from rogue skills). Validating a key against options computed
  // while the key is still answered therefore rejects the very ids `options`
  // offered. Re-resolve each answered key against a probe with that key removed.
  // Validate against the MAXIMAL option set — the choices as they stand before any
  // dynamic answer consumes one. `pendingChoices` de-duplicates: a skill you picked
  // disappears from its own list, and a downstream choice (rogue expertise draws
  // from rogue skills) removes more. Checking against the post-answer list rejects
  // the very ids `options` offered. Catching values absent from the CATALOG is what
  // this guard is for; over-picking and duplicates are the `ready` gate's job.
  const base = {};
  for (const k of Object.keys(answers)) if (META_KEYS.has(k) || cat.graph.steps.some((s) => s.nodes.some((n) => n.id === k))) base[k] = answers[k];

  for (const c of pendingChoices(cat, base)) known.add(c.id);
  for (const key of Object.keys(answers)) {
    if (META_KEYS.has(key) || key.startsWith("_")) continue;
    const c = pendingChoices(cat, base).find((x) => x.id === key);
    if (!c) continue;
    known.add(key);
    const legal = (c.options || []).map((o) => o.id);
    if (!legal.length) continue;
    const given = answers[key];
    const seen = new Set();
    for (const v of Array.isArray(given) ? given : [given]) {
      if (!legal.includes(v)) {
        problems.push(`Manquant documentaire : "${v}" is not available for "${key}" — not in the catalog, or another answer already grants it. Legal ids: ${legal.join(", ")}`);
      } else if (seen.has(v)) {
        problems.push(`"${v}" appears twice under "${key}" — each pick must be distinct.`);
      }
      seen.add(v);
    }
  }

  // A misspelled key is silently dropped by the resolver; say so rather than
  // letting the agent believe the answer registered.
  for (const key of Object.keys(answers)) {
    if (!known.has(key) && !key.startsWith("_")) {
      problems.push(`Unknown answer key "${key}" — it is ignored. Run \`options\` to see the exact ids.`);
    }
  }
  return problems;
}

/* ---- options : the next legal choices, straight from the resolver ---- */
/* ---- grounded facts on the three identity choices -------------------------
   `fixedNodeOptions` returns {id, name}, which is all the resolver needs and
   nothing a first-time player can choose from. The skill body used to send the
   agent to `data/classes.json` for a one-line description — 46161 characters,
   not shipped inside the skill folder — so in practice the opening turn came
   from memory. Every field below is COPIED from the catalog entry, never
   computed or reworded, and carries the entry's own ref + source so the
   citation travels with the value. Measured on the 12 classes: 3907 characters
   against 46161 for the file, and 448 for the bare {id, name}. */
const factsFor = (entry, catalogKey) => {
  const eff = entry.effects || [];
  const all = (what) => eff.filter((e) => e.what === what);
  const values = (what) => all(what).map((e) => e.value).filter(Boolean);
  const base = { ref: entry.ref, source: entry.source };

  if (catalogKey === "classes") {
    const cast = all("spellcasting")[0];
    return { ...base,
      hitDie: entry.hitDie,
      primaryAbility: entry.primaryAbility,
      savingThrows: entry.savingThrows,
      armorTraining: values("armorTraining"),
      shieldTraining: all("shieldTraining").length > 0,
      weaponProficiency: values("weaponProficiency"),
      spellcastingAbility: cast ? cast.ability : null,
      level1Features: all("feature").map((e) => e.name).filter(Boolean),
      subclassLevel: (entry.subclass || {}).level ?? null };
  }
  if (catalogKey === "species") {
    // Five of ten species — human, elf, dragonborn, tiefling, aasimar — carry an
    // empty effects[] because what distinguishes them is a CHOICE (a Dragonborn's
    // draconic ancestry, an Elf's lineage). Reporting only effects[] handed the
    // agent "darkvision, and nothing else" for the species a beginner names first,
    // which is precisely when it fills the hole from memory.
    const mappedChoices = (entry.choices || []).map((c) => ({
      id: c.id, kind: c.kind, count: c.count,
      options: (c.from && c.from.fromList) || Object.keys(c.appliesEffects || {}) }));
    const lineages = (entry.lineages || []).map((l) => l.name || l.id);
    // When lineages is empty but an ancetre-draconique choice is present, surface
    // it as a dedicated top-level field so an LLM does not see only `lineages: []`
    // and fall back to memory for the 10 draconic ancestry options.
    const draconicChoice = (entry.choices || []).find((c) => c.kind === "ancetre-draconique");
    const draconicAncestry = (lineages.length === 0 && draconicChoice)
      ? { kind: draconicChoice.kind,
          options: (draconicChoice.from && draconicChoice.from.fromList)
                   || Object.keys(draconicChoice.appliesEffects || {}) }
      : undefined;
    return { ...base,
      size: entry.size,
      speed: entry.speed,
      senses: all("sense").map((e) => [e.value, e.range].filter(Boolean).join(" ")),
      resistances: values("resistance"),
      features: all("feature").map((e) => e.name).filter(Boolean),
      choices: mappedChoices,
      lineages,
      ...(draconicAncestry ? { draconicAncestry } : {}) };
  }
  if (catalogKey === "backgrounds") {
    return { ...base,
      abilityScores: entry.abilityScores,
      skills: entry.skills,
      toolProficiency: entry.toolProficiency,
      feat: entry.feat };
  }
  return null;
};

/* Only the three nodes that draw straight from a catalog list — class, species,
   background. Subclass (level 3), lineage and ability method resolve from an
   already-made choice and need no card. */
function withFacts(cat, node, options) {
  const key = (node.optionsFrom || {}).catalog;
  const list = key && cat[key];
  if (!list) return options;
  return options.map((o) => {
    const entry = list.find((e) => e.id === o.id);
    const facts = entry && factsFor(entry, key);
    return facts ? { ...o, facts } : o;
  });
}

function cmdOptions(answers) {
  const catalog = loadCatalogNodeSync(); // resolver.loadCatalogNode is async; wrap below
  return catalog.then((cat) => {
    const fixed = [];
    for (const step of cat.graph.steps) {
      for (const node of step.nodes) {
        if (!nodeApplies(cat, answers, node)) continue;
        if (node.type === "single" && answers[node.id] == null) {
          fixed.push({ id: node.id, label: node.label, type: "single",
            options: withFacts(cat, node, fixedNodeOptions(cat, answers, node)) });
        } else if (node.type === "ability-scores" && !answers.abilityScores) {
          fixed.push({ id: "abilityScores", label: node.label, type: "ability-scores", methods: cat.graph.abilityMethods });
        }
      }
    }
    const dynamic = pendingChoices(cat, answers)
      .filter((c) => !c.satisfied)
      .map((c) => ({ id: c.id, kind: c.kind, source: c.sourceLabel, need: c.need,
        options: c.options, recommendations: c.recommendations }));
    const ready = fixed.length === 0 && dynamic.length === 0 && !!answers.abilityScores;
    return { ready, fixedPending: fixed, dynamicPending: dynamic };
  });
}

/* One shared, validated catalog per invocation. */
function loadCatalogNodeSync() {
  if (_catalog) return _catalog;
  _catalog = Promise.resolve({
    classes: loadData("classes.json"), subclasses: loadData("subclasses.json"),
    species: loadData("species.json"), backgrounds: loadData("backgrounds.json"),
    feats: loadData("feats.json"), equipment: loadData("equipment.json"),
    spells: loadData("spells.json"), spellsByClass: loadData("spells-by-class.json"),
    languages: loadData("languages.json"), conditions: loadData("conditions.json"),
    graph: loadData("build-graph.json"),
  });
  return _catalog;
}

/* ---- catalog cross-checks the pure engine cannot make (it never reads data/) ----
   A prepared spell above the highest slot level the class has at the sheet's level,
   or a "cantrip" that is not level 0 in the catalog, is a hard error. Slot ceilings
   come from data/progression.json (extracted from the class tables), spell levels
   from data/spells.json. Lists that are not a class in the progression (e.g. the
   species list) are outside class slots and are not capped here. */
function spellLevelProblems(C, catalog = null) {
  const problems = [];
  let spells, progression, byClass;
  try {
    spells = catalog ? catalog.spells : loadData("spells.json");
    progression = loadData("progression.json");
    byClass = catalog ? catalog.spellsByClass : loadData("spells-by-class.json");
  } catch { return problems; } // no catalog beside the engine: nothing to cross-check
  const byId = new Map(spells.map((s) => [s.id, s]));

  /* List membership was never checked anywhere, so a level-1 Cleric whose four
     chosen cantrips were Wizard-only — filed under `list: "cleric"` — linted
     clean and exited 0. Two skills define "legal" as "0 sheet-lint errors" and
     dnd-check's description promises to flag "a skill on the wrong list".

     Scoped deliberately: only the eight lists spells-by-class.json actually
     defines. A sheet's `list` is also legitimately `espece` (species-granted) or
     `initie-clerc` (the Magic Initiate feat), which name no catalog list. Mapping
     `initie-clerc` -> `cleric` would be a guess, and guessing is the one thing
     this engine refuses; those lists are reported as unverified instead. */
  const onList = new Map(Object.entries(byClass).map(([k, v]) => [k, new Set(v.map((e) => e.id))]));
  const unverified = new Set();
  const checkMembership = (s, kind) => {
    const set = onList.get(s.list);
    if (!set) { if (s.list) unverified.add(s.list); return; }
    if (!set.has(s.id)) {
      problems.push({ level: "error", code: "spell-list-membership",
        params: { kind, spell: s.id, list: s.list },
        msg: `${kind} ${s.id}: absent de la liste "${s.list}" (data/spells-by-class.json)` });
    }
  };
  const maxSlotFor = (list) => {
    const cls = progression.classes && progression.classes[list];
    const row = cls && cls.levels && cls.levels[(C.lvl || 1) - 1];
    if (!row) return null;
    if (row.pact) return row.pact.level;
    if (row.slots) return Math.max(...Object.keys(row.slots).map(Number));
    return 0;
  };
  for (const s of C.cantrips) {
    checkMembership(s, "sort mineur");
    const cat = byId.get(s.id);
    if (!cat) { problems.push({ level: "warn", code: "spell-catalog-missing",
      params: { kind: "cantrip", spell: s.id }, msg: `sort mineur ${s.id}: absent du catalogue (Manquant documentaire)` }); continue; }
    if (cat.level !== 0) problems.push({ level: "error", code: "cantrip-level-invalid",
      params: { spell: s.id, level: cat.level }, msg: `sort mineur ${s.id}: niveau ${cat.level} dans le catalogue, un sort mineur doit etre de niveau 0` });
  }
  for (const s of C.prepared) {
    checkMembership(s, "sort prepare");
    const cat = byId.get(s.id);
    if (!cat) { problems.push({ level: "warn", code: "spell-catalog-missing",
      params: { kind: "prepared spell", spell: s.id }, msg: `sort prepare ${s.id}: absent du catalogue (Manquant documentaire)` }); continue; }
    const max = maxSlotFor(s.list);
    if (max != null && cat.level > max) {
      problems.push({ level: "error", code: "spell-level-unavailable",
        params: { spell: s.id, level: cat.level, max, list: s.list, characterLevel: C.lvl },
        msg: `sort prepare ${s.id}: niveau ${cat.level} > emplacement max ${max} (${s.list} niveau ${C.lvl}, source: progression.json)` });
    }
  }
  // Say what was NOT checked rather than let a clean lint imply it was.
  if (unverified.size) {
    problems.push({ level: "warn", code: "spell-list-unverified",
      params: { lists: [...unverified].sort().join(", ") },
      msg: `appartenance non verifiee pour ${[...unverified].sort().join(", ")} : ces listes ne sont pas definies dans data/spells-by-class.json — a controler a la main` });
  }
  return problems;
}

/* ---- machine-readable summary of a computed character (for build/check --json) ---- */
function summarize(C) {
  return {
    id: C.model.id || null,
    classId: C.model.classId || null,
    speciesId: C.model.speciesId || null,
    lineageId: C.model.lineageId || null,
    backgroundId: C.model.backgroundId || null,
    identity: C.model.identity || {}, level: C.lvl, pb: C.PB,
    scores: C.scores, mods: C.mods,
    sources: C.model.sources || [], choices: C.model.choices || [],
    derived: C.derived, saves: C.saves, skills: C.skills,
    features: C.features, casting: C.castingRows,
    counters: C.counters,
    cantrips: C.cantrips, prepared: C.prepared,
    equipment: C.model.equipment || [],
    missing: C.missing, conflicts: C.conflicts, problems: C.problems,
  };
}

/* Older checked models predate the stable catalog IDs used by the renderers.
   Resolve them from catalog names only when the match is unique; an uncertain
   mapping stays visible as a structured warning instead of silently selecting
   the first plausible entry. */
function resolveLegacyModelIds(cat, model) {
  const legacyAliases = {
    classId: {
      barbare: "barbarian", barde: "bard", clerc: "cleric", druide: "druid",
      guerrier: "fighter", moine: "monk", paladin: "paladin", rodeur: "ranger",
      roublard: "rogue", ensorceleur: "sorcerer", occultiste: "warlock", magicien: "wizard",
    },
    speciesId: {
      drakeide: "dragonborn", nain: "dwarf", elfe: "elf", gnome: "gnome",
      goliath: "goliath", halfelin: "halfling", humain: "human", orc: "orc", tieffelin: "tiefling",
    },
    backgroundId: { acolyte: "acolyte", criminel: "criminal", sage: "sage", soldat: "soldier" },
  };
  const warnings = [];
  const warn = (field, value, reason) => warnings.push({
    level: "warn",
    code: "legacy-id-unresolved",
    params: { entity: field, label: value ?? "", reason },
    msg: `ancien modèle : ${field} "${value ?? ""}" ${reason === "ambiguous" ? "est ambigu" : "ne correspond à aucune entrée du catalogue"}`,
  });
  const resolveUnique = (entries, value, field) => {
    if (!value) return null;
    const wanted = normId(value);
    const alias = legacyAliases[field]?.[wanted];
    if (alias) {
      const matched = (entries || []).filter((entry) => entry.id === alias);
      if (matched.length === 1) return matched[0];
    }
    let matches = (entries || []).filter((entry) =>
      [entry.id, entry.name, entry.label].some((candidate) => candidate && normId(candidate) === wanted));
    if (!matches.length) {
      matches = (entries || []).filter((entry) =>
        [entry.id, entry.name, entry.label].some((candidate) => {
          const token = candidate ? normId(candidate) : "";
          return token && (wanted.startsWith(`${token}-`) || token.startsWith(`${wanted}-`));
        }));
    }
    if (matches.length === 1) return matches[0];
    warn(field, value, matches.length > 1 ? "ambiguous" : "missing");
    return null;
  };

  const cls = model.classId ? null : resolveUnique(cat.classes, model.identity?.className, "classId");
  const species = model.speciesId ? null : resolveUnique(cat.species, model.identity?.species, "speciesId");
  const background = model.backgroundId ? null : resolveUnique(cat.backgrounds, model.identity?.background, "backgroundId");
  if (cls) model.classId = cls.id;
  if (species) model.speciesId = species.id;
  if (background) model.backgroundId = background.id;

  if (!model.lineageId && model.identity?.lineage) {
    const lineages = (cat.species || []).flatMap((entry) =>
      (entry.lineages || []).map((lineage) => ({ ...lineage, speciesId: entry.id })));
    const lineage = resolveUnique(lineages, model.identity.lineage, "lineageId");
    if (lineage) model.lineageId = lineage.id;
  }

  const sourceCatalogs = {
    "class-level": [cat.classes, model.classId],
    species: [cat.species, model.speciesId],
    lineage: [(cat.species || []).flatMap((entry) => entry.lineages || []), model.lineageId],
    background: [cat.backgrounds, model.backgroundId],
    feat: [cat.feats, null],
    subclass: [cat.subclasses, null],
  };
  for (const source of model.sources || []) {
    if (source.catalogId) continue;
    if (source.id === "origine-langues") {
      source.catalogId = "origin-languages";
      continue;
    }
    const spec = sourceCatalogs[source.kind];
    if (!spec) continue;
    if (spec[1]) {
      source.catalogId = spec[1];
      continue;
    }
    const entry = resolveUnique(spec[0], source.label || source.id, `sources.${source.id}.catalogId`);
    if (entry) source.catalogId = entry.id;
  }

  const equipmentEntries = Object.values(cat.equipment || {})
    .filter(Array.isArray).flat();
  const roleIds = {
    bouclier: "shield", shield: "shield", armure: "armor", armor: "armor",
    arme: "weapon", weapon: "weapon", outil: "tool", tool: "tool",
    paquetage: "pack", pack: "pack", "focaliseur-dincantation": "spellcasting-focus",
    "spellcasting-focus": "spellcasting-focus", objet: "gear", gear: "gear",
  };
  for (const item of model.equipment || []) {
    let entry = null;
    if (!item.id) {
      entry = resolveUnique(equipmentEntries, item.object, `equipment.${item.object}.id`);
      if (entry) item.id = entry.id;
    } else {
      entry = equipmentEntries.find((candidate) => candidate.id === item.id) || null;
    }
    if (!item.roleIds && item.roles) {
      item.roleIds = item.roles.map((role) => roleIds[normId(role)]).filter(Boolean);
    }
    if (!item.damageType && entry?.damageType) item.damageType = entry.damageType;
  }
  return warnings;
}

/* ---- markdown sheet ---- */
function renderSheet(C, lang, labels) {
  const L = makeLabeler(lang, labels);
  const ui = loadUiLabels();
  const t = ui[lang] || ui.en || {};
  const id = C.model.identity || {};
  const A = ["str", "dex", "con", "int", "wis", "cha"];
  const out = [];

  const clsName = L.map("classes", (C.model.sources.find((s) => s.kind === "class-level") || {}).id, id.className);
  const spName = L.map("species", (C.model.sources.find((s) => s.kind === "species") || {}).id, id.species);
  out.push(`# ${id.name || "?"}`);
  out.push(`*${spName || "?"}${id.lineage ? " (" + id.lineage + ")" : ""}, ${clsName || "?"} ${t.level} ${C.lvl}${id.background ? ", " + id.background : ""}.*`);
  out.push("");

  // ability scores
  out.push("| " + A.map((a) => L.abil(a).slice(0, 3)).join(" | ") + " |");
  out.push("|" + A.map(() => "---").join("|") + "|");
  out.push("| " + A.map((a) => `${C.scores[a] ?? "?"} (${sign(C.mods[a])})`).join(" | ") + " |");
  out.push("");

  // core derived
  const pick = (name) => C.derived.find((d) => d.name === name);
  const core = [
    [t.pb, sign(C.PB), `PB`],
    [t.hp, (pick("Points de vie") || {}).value, (pick("Points de vie") || {}).prov],
    [t.ac, (pick("CA") || {}).value, (pick("CA") || {}).prov],
    [t.init, (pick("Initiative") || {}).value, `mod Dex`],
    [t.pp, (pick("Perception passive") || {}).value, (pick("Perception passive") || {}).prov],
  ];
  for (const [k, v, prov] of core) out.push(`- **${k}**: ${v} _(${t.provenance}: ${prov})_`);
  out.push("");

  // saves
  out.push(`## ${t.saves}`);
  out.push(C.saves.map((s) => `${L.abil(s.a).slice(0, 3)} ${sign(s.total)}${s.prof ? "*" : ""}`).join(" · "));
  out.push("");

  // skills (proficient only, to stay under Vercel-style volume discipline)
  const prof = C.skills.filter((s) => s.prof);
  if (prof.length) {
    out.push(`## ${t.skills}`);
    out.push(prof.map((s) => `${L.map("skills", s.name, s.name)} ${sign(s.total)}${s.exp ? "**" : "*"} _(${s.src || ""})_`).join("\n"));
    out.push("");
  }

  // features
  if (C.features && C.features.length) {
    out.push(`## ${t.features}`);
    out.push(C.features.map((f) => `- **${f.name}**${f.note ? `: ${f.note}` : ""} _(${f.src || ""})_`).join("\n"));
    out.push("");
  }

  // proficiencies: armor / weapons / shield
  const armorLine = (C.armorTraining || []).join(", ");
  const weaponLine = (C.weaponProf || []).map((w) => w.v).join(", ");
  const shieldLine = C.hasShieldTraining ? t.shield : "";
  if (armorLine || weaponLine || shieldLine) {
    out.push(`## ${t.proficiencies}`);
    if (armorLine) out.push(`**${t.armor}**: ${armorLine}`);
    if (weaponLine) out.push(`**${t.weapons}**: ${weaponLine}`);
    if (shieldLine) out.push(`**${shieldLine}**`);
    out.push("");
  }

  // tools
  if (C.tools && C.tools.length) {
    out.push(`## ${t.tools}`);
    out.push(C.tools.map((tl) => `- ${tl.v} _(${tl.src || ""})_`).join("\n"));
    out.push("");
  }

  // languages
  if (C.languages && C.languages.length) {
    out.push(`## ${t.languages}`);
    out.push(C.languages.map((lg) => `- ${lg.v} _(${lg.src || ""})_`).join("\n"));
    out.push("");
  }

  // spells
  if (C.cantrips.length || C.prepared.length) {
    out.push(`## ${t.spells}`);
    C.castingRows.forEach((r) => out.push(`- ${r.list}: DC ${r.dc} / atk ${sign(r.atk)}`));
    if (C.cantrips.length) out.push(`**${t.cantrips}**: ` + C.cantrips.map((s) => L.map("spells", s.id, s.label || s.id)).join(", "));
    if (C.prepared.length) out.push(`**${t.prepared}**: ` + C.prepared.map((s) => L.map("spells", s.id, s.label || s.id)).join(", "));
    out.push("");
  }

  // equipment
  if ((C.model.equipment || []).length) {
    out.push(`## ${t.equipment}`);
    out.push(C.model.equipment.map((e) => `- ${e.object} (${(e.roles || []).join(", ")})`).join("\n"));
    out.push("");
  }

  // combat summary (niveau 1)
  // All values are grounded: counters from progression.json, spell counts from
  // the built model, slots from progression.json. Nothing is inferred from memory.
  const classSrc = C.model.sources.find((s) => s.kind === "class-level");
  if (classSrc) {
    const classId = classSrc.id;
    let lvl1 = null;
    try {
      const prog = loadData("progression.json");
      const cls = prog && prog.classes && prog.classes[classId];
      lvl1 = cls && cls.levels && cls.levels[0];
    } catch { /* progression.json unavailable: skip combat section */ }

    if (lvl1) {
      out.push(`## ${t.combat}`);

      // 1. Standard actions. No structured action-type effects exist in the catalog
      //    (effects[] carries grants/requires/requiresChoice but no "action" what).
      //    The spec instructs to show the standard line when no special action data
      //    is present — this is the fallback, not an invented value.
      out.push(`- **${t.actions}** : ${t.actionsStd}`);

      // 2. Resources: named counters at level 1 from the class table.
      //    provenance: progression.json → classId, level 1.
      const cEntries = Object.entries(lvl1.counters || {});
      if (cEntries.length) {
        const resLine = cEntries.map(([k, v]) => `${k} × ${v}`).join(", ");
        out.push(`- **${t.resources}** : ${resLine} _(${t.provenance}: progression.json → ${classId})_`);
      }

      // 3. Spells: only for classes that have casting rows in the model.
      if (C.castingRows && C.castingRows.length) {
        const spellParts = [];
        const cantripCount = C.cantrips.length;
        const preparedCount = C.prepared.length;
        if (cantripCount) spellParts.push(`${cantripCount} ${t.cantrips.toLowerCase()}`);
        if (preparedCount) spellParts.push(`${preparedCount} ${t.prepared.toLowerCase()}`);
        const slots = lvl1.slots || {};
        if (Object.keys(slots).length) {
          const slotStr = Object.entries(slots).map(([sl, n]) => `niv.${sl}×${n}`).join(", ");
          spellParts.push(`${t.slots} : ${slotStr}`);
        }
        const pact = lvl1.pact || {};
        if (pact.slots) {
          spellParts.push(`${t.pactSlots} : ${pact.slots}×niv.${pact.level}`);
        }
        if (spellParts.length) {
          out.push(`- **${t.spells}** : ${spellParts.join(", ")} _(${t.provenance}: progression.json → ${classId})_`);
        }
      }

      out.push("");
    }
  }

  // remaining / conflicts / lint
  out.push(`## Lint`);
  out.push(`- ${t.remaining}: ${C.missing.length ? C.missing.map((m) => `${m.kind}×${m.count}`).join(", ") : t.none}`);
  out.push(`- ${t.conflicts}: ${C.conflicts.length ? C.conflicts.map((c) => c.what).join(", ") : t.none}`);
  const errs = C.problems.filter((p) => p.level === "error");
  out.push(errs.length ? `- ⛔ ${errs.length} ${t.lintErr}: ${errs.map((p) => p.msg).join(" ; ")}` : `- ✅ ${t.lintOk}`);
  // Warnings were computed and then dropped from the rendered sheet, so the
  // engine's own "Manquant documentaire" never reached anyone — which is how a
  // shipped reference character carried a spell id that exists nowhere in the
  // catalog. A clean-looking sheet must not hide what the engine could not verify.
  const warns = C.problems.filter((p) => p.level === "warn");
  if (warns.length) out.push(`- ⚠ ${warns.length} avertissement(s): ${warns.map((p) => p.msg).join(" ; ")}`);
  return out.join("\n");
}

/* ---- runners ---- */
/* Exit 2 is reserved for "the engine/bundle is missing" (the shim owns it), so
   input and usage errors exit 3. A raw stack trace costs the agent a turn and
   names files it was never told about, so every read failure is one line. */
const USAGE = 3;

/* Indentation doubles every payload — the opening `options` call is 25818 characters
   pretty against 13048 compact, and harnesses truncate silently between 10K and 30K.
   Indent only what is small enough to stay well outside that band; JSON.parse does
   not care either way. */
function emit(obj) {
  const compact = JSON.stringify(obj);
  console.log(compact.length > 8000 ? compact : JSON.stringify(obj, null, 2));
}

const COMMANDS = ["options", "build", "check", "progression", "doctor"];
const LANGS = ["en", "fr", "de", "es", "it", "ja", "ru", "zh", "ar"];

function packageVersion() {
  try {
    const version = JSON.parse(readFileSync(new URL("../version.json", import.meta.url), "utf8"));
    if (typeof version.version === "string" && version.version) return version.version;
  } catch { /* installed legacy bundles may not carry version.json */ }
  return "unknown";
}

function parseGlobalArgs(argv) {
  const rest = [];
  let catalog = null;
  let version = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--version") {
      if (version) throw new Error("--version was provided more than once");
      version = true;
      continue;
    }
    if (arg === "--catalog" || arg.startsWith("--catalog=")) {
      if (catalog !== null) throw new Error("--catalog was provided more than once");
      const inline = arg.startsWith("--catalog=") ? arg.slice("--catalog=".length) : null;
      const value = inline !== null ? inline : argv[++i];
      if (!value || value.startsWith("--")) throw new Error("--catalog requires a directory path");
      catalog = value;
      continue;
    }
    rest.push(arg);
  }
  if (version && rest.length) throw new Error("--version cannot be combined with a command or other arguments");
  return { argv: rest, catalog, version };
}

/* "Reject ambiguous input with a clear error rather than guessing." A mistyped flag
   used to be ignored: `build --jsonn` printed a markdown sheet and exited 0, so an
   agent that asked for JSON got prose with nothing to tell it why. */
const FLAGS = {
  options: ["--brief", "--only"],
  build: ["--format", "--lang", "--output", "--json"],
  check: ["--format", "--lang", "--output", "--json"],
  progression: [], doctor: ["--json"],
};
function rejectUnknownFlags(cmd, rest) {
  const legal = FLAGS[cmd] || [];
  for (const a of rest) {
    if (!a.startsWith("--")) continue;
    const name = a.split("=")[0];
    if (legal.includes(name)) continue;
    console.error(`dnd: unknown flag "${name}" for \`${cmd}\`. Legal flags: ${legal.join(" ") || "(none)"}.`);
    process.exit(USAGE);
  }
}

function readJSON(path) {
  let raw;
  try {
    raw = readFileSync(path, "utf8");
  } catch (e) {
    const why = e.code === "ENOENT" ? "no such file" : e.code === "EISDIR" ? "that is a directory" : e.code;
    console.error(`dnd: cannot read "${path}" (${why}). Expected a JSON file.`);
    process.exit(USAGE);
  }
  try {
    return JSON.parse(raw);
  } catch (e) {
    console.error(`dnd: "${path}" is not valid JSON (${e.message}).`);
    process.exit(USAGE);
  }
}

/* --lang accepts a closed set. Guessing silently is how `--lang=en` came to
   render French and `--lang klingon` to render English, both exiting 0. */
function parseLang(rest) {
  let value = null;
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    if (a === "--lang") { value = rest[i + 1] ?? ""; break; }
    if (a.startsWith("--lang=")) { value = a.slice("--lang=".length); break; }
  }
  if (value === null) return "en";
  if (!LANGS.includes(value)) {
    console.error(`dnd: unknown --lang "${value}". Legal values: ${LANGS.join(" ")}.`);
    process.exit(USAGE);
  }
  return value;
}

/* build/check share one closed, strict output contract. Values may use either
   `--flag value` or `--flag=value`; duplicate/conflicting declarations are
   rejected instead of depending on argument order. */
function parseRenderOptions(rest, cmd) {
  let lang = null;
  let format = null;
  let output = null;
  let jsonAlias = false;

  const setOnce = (name, current, value) => {
    if (current !== null) {
      console.error(`dnd: ${name} was provided more than once.`);
      process.exit(USAGE);
    }
    return value;
  };
  const takeValue = (arg, name, i) => {
    if (arg === name) {
      const value = rest[i + 1];
      if (value == null || value.startsWith("--")) {
        console.error(`dnd: ${name} requires a value.`);
        process.exit(USAGE);
      }
      return { value, consumed: 1 };
    }
    if (arg.startsWith(name + "=")) return { value: arg.slice(name.length + 1), consumed: 0 };
    return null;
  };

  for (let i = 0; i < rest.length; i++) {
    const arg = rest[i];
    if (arg === "--json") {
      if (jsonAlias) {
        console.error("dnd: --json was provided more than once.");
        process.exit(USAGE);
      }
      jsonAlias = true;
      continue;
    }
    let parsed = takeValue(arg, "--lang", i);
    if (parsed) {
      lang = setOnce("--lang", lang, parsed.value);
      i += parsed.consumed;
      continue;
    }
    parsed = takeValue(arg, "--format", i);
    if (parsed) {
      format = setOnce("--format", format, parsed.value);
      i += parsed.consumed;
      continue;
    }
    parsed = takeValue(arg, "--output", i);
    if (parsed) {
      output = setOnce("--output", output, parsed.value);
      i += parsed.consumed;
      continue;
    }
    const legal = FLAGS[cmd].join(" ");
    console.error(arg.startsWith("--")
      ? `dnd: unknown flag "${arg.split("=")[0]}" for \`${cmd}\`. Legal flags: ${legal}.`
      : `dnd: unexpected argument "${arg}" for \`${cmd}\`.`);
    process.exit(USAGE);
  }

  lang ||= "en";
  if (!LANGS.includes(lang)) {
    console.error(`dnd: unknown --lang "${lang}". Legal values: ${LANGS.join(" ")}.`);
    process.exit(USAGE);
  }
  if (format !== null && !["html", "markdown", "json"].includes(format)) {
    console.error(`dnd: unknown --format "${format}". Legal values: html markdown json.`);
    process.exit(USAGE);
  }
  if (jsonAlias && format !== null && format !== "json") {
    console.error(`dnd: --json conflicts with --format ${format}. Use one output format.`);
    process.exit(USAGE);
  }
  format = jsonAlias ? "json" : (format || (cmd === "build" ? "html" : "markdown"));
  if (output !== null && format === "json") {
    console.error("dnd: --output cannot be used with JSON output; JSON is written to stdout.");
    process.exit(USAGE);
  }
  return { lang, format, output };
}

function standaloneAssets() {
  const css = readFileSync(new URL("../assets/ds.css", import.meta.url), "utf8");
  const print = readFileSync(new URL("../assets/ds.print.css", import.meta.url), "utf8");
  const js = readFileSync(new URL("../assets/ds.js", import.meta.url), "utf8");
  // A standalone document must not retain ds.css's relative print dependency.
  const expandedCss = css.replace(
    /^\s*@import\s+["']ds\.print\.css["']\s+print\s*;\s*/m,
    `\n@media print {\n${print}\n}\n`,
  );
  return { css: expandedCss, js };
}

function displaySource(file) {
  const rel = relative(process.cwd(), resolve(file));
  return (rel || basename(resolve(file))).replaceAll("\\", "/");
}

function defaultOutputPath(file, cmd, lang, format) {
  const absoluteInput = resolve(file);
  const fileName = basename(absoluteInput);
  const suffix = cmd === "build" ? ".answers.json" : ".character.json";
  const stem = fileName.toLowerCase().endsWith(suffix)
    ? fileName.slice(0, -suffix.length)
    : fileName.toLowerCase().endsWith(".json")
      ? fileName.slice(0, -5)
      : fileName;
  const kind = cmd === "build" ? "sheet" : "audit";
  const extension = format === "html" ? "html" : "md";
  return resolve(dirname(absoluteInput), `${stem}.${kind}.${lang}.${extension}`);
}

function resolveOutputPath(file, cmd, options) {
  const outputPath = options.output
    ? resolve(options.output)
    : defaultOutputPath(file, cmd, options.lang, options.format);
  if (outputPath === resolve(file)) {
    console.error("dnd: refusing to overwrite the input file; choose a different --output path.");
    process.exit(USAGE);
  }
  const wanted = options.format === "html" ? ".html" : ".md";
  if (extname(outputPath).toLowerCase() !== wanted) {
    console.error(`dnd: ${options.format} output must use the "${wanted}" extension.`);
    process.exit(USAGE);
  }
  return outputPath;
}

/* ---- doctor : report the installation as it actually is ------------------
   Every count here is read from disk at call time. The alternative — writing
   the numbers into prose — is what let the skill pack ship a stale roster and
   stale catalog counts: duplicated state always drifts, and nothing notices. */
// Every file the resolver actually needs. Omitting build-graph/equipment/
// spells-by-class made doctor report a healthy bundle that could not build a
// single sheet — the one situation the command exists to detect.
// `Object.keys(j).length` is right only for a flat id->entry map. Applied to a
// grouped file it counts the *groups* — doctor reported "3 languages" for 19 and
// "6 equipment" for 131, and a test that recomputed with the same expression
// could not notice. Each grouped file therefore names its own counter, and
// `show: false` keeps plumbing (the build graph, the per-class spell index) out
// of the human line while still health-checking it.
const sumGroups = (skip) => (j) =>
  Object.entries(j).reduce((n, [k, v]) => (skip.includes(k) || !Array.isArray(v) ? n : n + v.length), 0);

const ENTITY_FILES = [
  ["classes", "classes.json"], ["subclasses", "subclasses.json"], ["species", "species.json"],
  ["backgrounds", "backgrounds.json"], ["feats", "feats.json"], ["spells", "spells.json"],
  ["conditions", "conditions.json"],
  ["languages", "languages.json", sumGroups(["ref"])],
  ["equipment", "equipment.json", sumGroups(["_meta"])],
  ["spellsByClass", "spells-by-class.json", (j) => Object.keys(j).length, false],
  ["graphSteps", "build-graph.json", (j) => (j.steps || []).length, false],
];
const LANGS_ALL = ["en", "fr", "de", "es", "it", "ja", "ru", "zh", "ar"];

function cmdDoctor() {
  const selected = _catalogConfig || configureCatalog();
  const manifest = selected.manifest || {};
  const report = {
    healthy: selected.errors.length === 0,
    node: process.version,
    version: packageVersion(),
    engine: fileURLToPath(import.meta.url),
    catalog: selected.dir,
    catalogPath: selected.dir,
    catalogSource: selected.source,
    catalogManifest: selected.manifestPath,
    manifestValid: selected.errors.length === 0,
    catalogSchemaVersion: manifest.schemaVersion ?? null,
    catalogProfile: manifest.profile ?? null,
    catalogVersion: manifest.version ?? null,
    catalogRuleset: manifest.ruleset ?? null,
    catalogLicense: manifest.license ?? null,
    license: manifest.license ?? null,
    counts: {},
    labels: {},
    warnings: [...selected.errors, ...selected.warnings],
  };

  for (const [name, f, count] of ENTITY_FILES) {
    try {
      const j = loadData(f);
      report.counts[name] = count ? count(j) : Array.isArray(j) ? j.length : Object.keys(j).length;
      // "Readable" is not "usable": an empty array parses fine and resolves nothing.
      if (!report.counts[name]) {
        report.healthy = false;
        report.warnings.push(`data/${f} parses but is empty — the engine cannot resolve anything from it`);
      }
    } catch {
      report.counts[name] = null;
      report.healthy = false;
      report.warnings.push(`catalog file missing or unreadable: data/${f}`);
    }
  }

  try { report.counts.progressionClasses = Object.keys(loadData("progression.json").classes || {}).length; }
  catch { report.counts.progressionClasses = null; report.warnings.push("data/progression.json missing — level 1-20 milestones unavailable"); }

  // Label coverage, per language, against the union of groups any language has.
  const groupsSeen = new Set();
  const perLang = {};
  for (const l of LANGS_ALL) {
    try {
      const j = loadData(`labels.${l}.json`);
      const groups = Object.keys(j).filter((k) => !k.startsWith("_"));
      groups.forEach((g) => groupsSeen.add(g));
      perLang[l] = groups;
    } catch { perLang[l] = null; report.warnings.push(`missing display labels: data/labels.${l}.json`); }
  }
  for (const l of LANGS_ALL) {
    if (!perLang[l]) { report.labels[l] = null; continue; }
    // `abil()` carries a hardcoded English table, so a missing `abilities` group
    // costs an English reader nothing. Reporting it anyway produced the useless
    // "those names fall back to English" against labels.en.json.
    const covered = (g) => perLang[l].includes(g) || (l === "en" && g === "abilities");
    const missing = [...groupsSeen].filter((g) => !covered(g));
    report.labels[l] = { groups: perLang[l].length, missingGroups: missing };
    // The catalog is authored in French, so an untranslated name is shown as-is —
    // French for every group but `abilities`, which has an English fallback table.
    if (missing.length) report.warnings.push(`labels.${l}.json has no ${missing.join(", ")} group — those names are shown untranslated`);
  }
  /* The loop above measures each language against `groupsSeen` — the union of
     what some language happens to have. A group absent from all nine is
     therefore invisible to it, which is how `feats` and `conditions` came to
     have zero labels in every language while doctor reported nine complete.
     The catalog files are the honest denominator: an entity type with no labels
     cannot be looked up by an English (or German, or Japanese) name at all. */
  const LABELLED = [["feats", "feats.json"], ["conditions", "conditions.json"],
    ["spells", "spells.json"], ["classes", "classes.json"], ["species", "species.json"],
    ["backgrounds", "backgrounds.json"], ["subclasses", "subclasses.json"]];
  report.unlabelled = [];
  for (const [group, f] of LABELLED) {
    if (report.counts[group] == null) continue;
    const anywhere = LANGS_ALL.some((l) => perLang[l] && perLang[l].includes(group));
    if (!anywhere) {
      report.unlabelled.push(group);
      report.warnings.push(
        `no language has a "${group}" label group — those ${report.counts[group]} entries are ` +
        `reachable only by their catalog (French) name, whatever --lang says`);
    }
  }

  /* Metadata is not text. Every spell carries level/school/range/components and
     no description, so "what does this spell do" has no catalog answer — the
     single question most likely to be filled in from memory. */
  try {
    const sp = loadData("spells.json");
    const list = Array.isArray(sp) ? sp : Object.values(sp);
    const DESC = ["description", "desc", "text", "effect", "effects", "summary"];
    if (list.length && !list.some((s) => DESC.some((k) => s[k]))) {
      report.warnings.push(
        `data/spells.json carries metadata only (level, school, range, components, classes) — ` +
        `no spell effect text. Answer "what does it do" with "Manquant documentaire", never from memory`);
    }
  } catch { /* the per-file loop above already recorded this */ }

  return report;
}

async function run() {
  if (process.argv.slice(2).length === 1 && process.argv[2] === "--help") {
    console.log(`Dungeons & Skills ${packageVersion()}
Level-1 D&D 2024 builder/checker using the bundled SRD 5.2.1 catalog.
Progression lookup covers class milestones at levels 1-20.

Usage:
  node engine/cli.mjs options <answers.json> [--catalog DIR]
  node engine/cli.mjs build <answers.json> [--format html|markdown|json] [--lang CODE] [--output FILE] [--catalog DIR]
  node engine/cli.mjs check <character.json> [--format html|markdown|json] [--lang CODE] [--output FILE] [--catalog DIR]
  node engine/cli.mjs progression <classId|subclassId> [--catalog DIR]
  node engine/cli.mjs doctor [--json] [--catalog DIR]
  node engine/cli.mjs --version`);
    return;
  }
  let invocation;
  try {
    invocation = parseGlobalArgs(process.argv.slice(2));
  } catch (error) {
    console.error(`dnd: ${error.message}.`);
    process.exit(USAGE);
  }
  if (invocation.version) {
    console.log(`dungeons-and-skills ${packageVersion()}`);
    return;
  }
  configureCatalog(invocation.catalog);
  const [cmd, file, ...rest] = invocation.argv;

  if (cmd === "doctor") {
    // Three skill bodies documented "exit 3 -> you mistyped the command; doctor
    // takes no arguments". doctor ignored them and exited 0, so the branch was
    // unreachable and `doctor --lang en` silently did nothing.
    const doctorArgs = invocation.argv.slice(1);
    const extra = doctorArgs.filter((a) => a !== "--json");
    if (extra.length) {
      console.error(`dnd: doctor takes no arguments (got ${extra.map((a) => JSON.stringify(a)).join(" ")}). ` +
        "It reads the catalog off disk and reports what is there; --lang does not apply.");
      process.exit(USAGE);
    }
    const r = cmdDoctor();
    if (doctorArgs.includes("--json")) {
      console.log(JSON.stringify(r, null, 2));
    } else {
      console.log(`Dungeons & Skills — installation report`);
      console.log(`  node     ${r.node}`);
      console.log(`  version  ${r.version}`);
      console.log(`  engine   ${r.engine}`);
      console.log(`  catalog  ${r.catalog} (${r.catalogSource})`);
      console.log(`  profile  ${r.catalogProfile || "?"} catalog ${r.catalogVersion || "?"} schema ${r.catalogSchemaVersion ?? "?"}`);
      // The human line lists what a player would recognise; `--json` carries
      // everything, plumbing included.
      const hidden = new Set(ENTITY_FILES.filter(([, , , show]) => show === false).map(([n]) => n));
      const shown = Object.entries(r.counts).filter(([k]) => !hidden.has(k));
      console.log(`  catalog contents: ${shown.map(([k, v]) => `${v ?? "?"} ${k}`).join(", ")}`);
      const ok = Object.entries(r.labels).filter(([, v]) => v && !v.missingGroups.length).map(([k]) => k);
      console.log(`  display languages complete: ${ok.join(" ") || "none"}`);
      for (const w of r.warnings) console.log(`  ! ${w}`);
      console.log(r.healthy ? "  => the rules bundle is installed and readable." : "  => the rules bundle is NOT usable.");
    }
    // Exit 2 means one thing: no usable bundle at all. An engine and a data/ that
    // are both present but missing one file is a different failure — the other files
    // ARE readable, so the bodies' "only just proven absent" reasoning does not apply.
    const nothingReadable = Object.entries(r.counts)
      .filter(([k]) => k !== "progressionClasses").every(([, v]) => !v);
    process.exit(r.healthy ? 0 : _catalogConfig?.manifest ? 1 : nothingReadable ? 2 : 1);
  }

  const renderOptions = (cmd === "build" || cmd === "check")
    ? parseRenderOptions(rest, cmd)
    : null;
  const lang = renderOptions ? renderOptions.lang : parseLang(rest);
  if (cmd && !renderOptions) rejectUnknownFlags(cmd, rest);
  if (!cmd || !file) {
    console.error(`usage: node engine/cli.mjs <${COMMANDS.join("|")}> <file.json|classId> ` +
      `[--format html|markdown|json] [--lang en] [--output file] [--json] [--catalog dir]`);
    process.exit(USAGE);
  }
  if (COMMANDS.includes(cmd) && _catalogConfig.errors.length) {
    for (const error of _catalogConfig.errors) console.error(`dnd: catalog error: ${error}`);
    process.exit(_catalogConfig.manifest ? 1 : 2);
  }

  if (cmd === "options") {
    const answers = readJSON(file);
    const cat = await loadCatalogNodeSync();
    const invalid = await validateAnswers(cat, answers);
    let res = await cmdOptions(answers);

    // A full spell list pushes one call past 15K chars, and answering one choice
    // at a time reaches ~136K cumulative — inside the band where harnesses
    // truncate silently, which would hand the agent a partial legal option set.
    const only = rest.includes("--only") ? rest[rest.indexOf("--only") + 1] : null;
    if (only) {
      res = { ...res, fixedPending: res.fixedPending.filter((c) => c.id === only),
              dynamicPending: res.dynamicPending.filter((c) => c.id === only) };
      if (!res.fixedPending.length && !res.dynamicPending.length) {
        console.error(`dnd: no pending choice with id "${only}". Run \`options\` with no --only to list them.`);
        process.exit(USAGE);
      }
    }
    if (rest.includes("--brief")) {
      const strip = (c) => ({ id: c.id, kind: c.kind, source: c.source, need: c.need,
                              optionCount: (c.options || []).length });
      res = { ...res, fixedPending: res.fixedPending.map((c) => ({ id: c.id, label: c.label, optionCount: (c.options || []).length })),
              dynamicPending: res.dynamicPending.map(strip) };
    }
    // Diagnostics on stderr so stdout stays pure JSON for the agent to parse.
    for (const p of invalid) console.error(`dnd: ${p}`);
    console.log(JSON.stringify({ ...res, invalidAnswers: invalid }, null, 2));
    process.exit(invalid.length ? 1 : 0);
  }

  if (cmd === "progression") {
    const id = file; // here the argument is a class/subclass id, not a file
    const prog = loadData("progression.json");
    if (prog.classes && prog.classes[id]) {
      console.log(JSON.stringify({ class: id, ...prog.classes[id] }, null, 2));
      process.exit(0);
    }
    const sub = loadData("subclasses.json").find((s) => s.id === id);
    if (sub) {
      const featuresByLevel = {};
      for (const e of sub.effects || []) {
        if (e.what === "feature" && e.level) (featuresByLevel[e.level] ||= []).push(e.name);
      }
      console.log(JSON.stringify({
        subclass: id, parentClass: sub.parentClass, unlockedAtLevel: sub.level,
        source: sub.source, ref: sub.ref, featuresByLevel,
      }, null, 2));
      process.exit(0);
    }
    console.error(`Manquant documentaire : "${id}" n'est ni une classe ni une sous-classe du catalogue.`);
    process.exit(1);
  }

  if (cmd === "build" || cmd === "check") {
    let catalogGaps = [];
    let legacyWarnings = [];
    let model;
    const cat = await loadCatalogNodeSync();
    if (cmd === "build") {
      const answers = readJSON(file);

      // An illegal value must never reach the sheet: it computes from nothing
      // and renders `undefined` under a green lint.
      const invalid = await validateAnswers(cat, answers);
      if (invalid.length) {
        for (const p of invalid) console.error(`dnd: ${p}`);
        console.error("dnd: refusing to build from illegal answers.");
        process.exit(1);
      }

      // `build` used to ignore `ready`, so an unfinished file produced a sheet
      // that reported "no remaining choices" and 0 lint errors while silently
      // defaulting scores to 10 and merging every equipment package.
      const state = await cmdOptions(answers);
      if (!state.ready) {
        const pending = [
          ...state.fixedPending.map((f) => f.id),
          ...state.dynamicPending.map((d) => d.id),
        ];
        console.error(`dnd: answers are incomplete — ${pending.length} choice(s) still pending: ${pending.join(", ")}.`);
        console.error("dnd: run `options` and answer them; a sheet built from an incomplete file is not legal even when the lint is clean.");
        process.exit(1);
      }
      model = toCharacterModel(cat, answers);
    } else {
      model = readJSON(file);
      if (!model || !Array.isArray(model.sources)) {
        console.error(`dnd: "${file}" is not a character model (no \`sources\` array).`);
        console.error("dnd: if this is an answers file, use `build` instead; `check` expects a built model.");
        process.exit(USAGE);
      }

      // An empty model has nothing to audit; recomputing it printed `undefined`
      // values under a clean lint.
      if (!model.sources.length) {
        console.error("dnd: the `sources` array is empty — there is no character to check.");
        process.exit(USAGE);
      }
      legacyWarnings = resolveLegacyModelIds(cat, model);

      // `check` recomputes whatever it is handed, so a sheet naming entities the
      // catalog does not define used to lint clean. Report them — do not refuse:
      // an absent entry is "Manquant documentaire" for the audit to relay, not a
      // rules violation. Source ids are DERIVED (`druide-1`, not `druid`), so this
      // matches on the catalog id being contained in the source id, and stays a
      // warning precisely because that match is approximate.
      //
      // Source ids are DERIVED FROM THE FRENCH NAME (`clerc-1`, `tieffelin-abyssal`)
      // while catalog ids are English slugs (`cleric`, `tiefling`). Matching on the
      // id alone therefore flagged every correctly built character, including both
      // shipped under docs/characters/ — and a false "Manquant documentaire" on a
      // legal sheet is exactly the mistake the audit exists to avoid. Match a slug
      // of the entity's own `name` too.
      const slug = (v) => String(v || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "")
        .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
      const known = [];
      for (const e of [...cat.classes, ...cat.subclasses, ...cat.species, ...cat.backgrounds, ...cat.feats]) {
        known.push(e.id, slug(e.name));
        for (const l of e.lineages || []) known.push(l.id, slug(l.name));
      }
      catalogGaps = model.sources
        .filter((s) => ["class-level", "subclass", "species", "lineage", "background", "feat"].includes(s.kind))
        .filter((s) => s.id !== "origine-langues")
        .filter((s) => {
          if (s.catalogId && known.includes(s.catalogId)) return false;
          const id = slug(s.id);
          return !known.some((k) => k && (id === k || id.startsWith(k + "-")));
        })
        .map((s) => `${s.kind} "${s.id}"`);
      for (const u of catalogGaps) {
        console.error(`dnd: Manquant documentaire : ${u} matches no catalog entry — report it as a gap, not as an illegal value.`);
      }
    }
    const C = computeCharacter(model);
    C.problems.push(...legacyWarnings);
    C.problems.push(...spellLevelProblems(C, cat));
    if (renderOptions.format === "json") {
      // A gap visible only on stderr is invisible to an agent capturing stdout —
      // which is what `--json` is for, and what dnd-check's workflow tells it to do.
      // It saw `problems: []` on a sheet carrying a Pathfinder feat.
      const summary = summarize(C);
      const gapProblems = catalogGaps.map((detail) => ({
        level: "warn", code: "catalog-gap", params: { detail },
        msg: `Manquant documentaire : ${detail}`,
      }));
      emit({ ...summary, problems: [...summary.problems, ...gapProblems], catalogGaps });
    } else {
      const labels = loadLabels(lang);
      const context = {
        lang,
        labels,
        fallbackLabels: loadLabels("en"),
        ui: loadUiLabels(),
        mode: "standalone",
        source: displaySource(file),
        catalogGaps,
      };
      if (renderOptions.format === "html") {
        for (const problem of C.problems) {
          const level = problem.level === "error" ? "error" : "warning";
          console.error(`dnd: ${level}: ${problem.msg}`);
        }
        const outPath = resolveOutputPath(file, cmd, renderOptions);
        mkdirSync(dirname(outPath), { recursive: true });
        writeFileSync(outPath, renderHTML(C, { ...context, assets: standaloneAssets() }), "utf8");
        console.log(`${cmd === "build" ? "sheet" : "audit"}: ${outPath}`);
      } else {
        const markdown = renderMarkdown(C, context);
        if (renderOptions.output) {
          const outPath = resolveOutputPath(file, cmd, renderOptions);
          mkdirSync(dirname(outPath), { recursive: true });
          writeFileSync(outPath, markdown, "utf8");
        }
        console.log(markdown);
      }
    }
    const errs = C.problems.filter((p) => p.level === "error");
    // An audit that cannot be told from a clean one by its exit code is not an audit.
    process.exit(errs.length || catalogGaps.length ? 1 : 0);
  }

  // Exit 2 means one thing only: the rules bundle is absent. It used to also mean
  // "unknown command", so `options` typed `option` licensed the degraded mode the
  // skills gate on exit 2 — a typo authorising D&D-from-memory.
  console.error(`dnd: unknown command "${cmd}". Legal commands: ${COMMANDS.join(" ")}.`);
  process.exit(USAGE);
}

// A crash is a bug in the engine, not a missing bundle and not a bad sheet; it
// gets its own code so no skill mistakes it for either.
run().catch((e) => { console.error(`dnd: internal error — ${e.stack || String(e)}`); process.exit(4); });
